### PR TITLE
Filter now returns a LogStash::Event according to the new logstash model...

### PR DESCRIPTION
**Pull request by barravi**
https://github.com/logstash-plugins/logstash-filter-zeromq/issues/2 It should fix this issue.

### CODE REVIEW

**Comment by ph** [comment]
Thank you for the pull request!

Would you mind doing step 2 of the contributing guide? https://github.com/elasticsearch/logstash/blob/master/CONTRIBUTING.md#contribution-steps

**Comment by barravi** [comment]
Done. SOrry for the delay it's my first pull request to ES.

**Comment by ph** [comment]
@barravi did you use the email in the patch when you signed the cla https://github.com/logstash-plugins/logstash-filter-zeromq/pull/3.patch ?

**Comment by barravi** [comment]
sorry no, I used my github email (slashvee at gmail dot com)

**Comment by ph** [comment]
@barravi Sorry for the delay we have been in a crunch time to address the last issues in 1.5.

I've checked with the other contributors and would you mind signing the CLA with the corporate email you used when you created this patch? I know it's a simple patch and it is confirmed to work, but we use our CLA database and the commits in the history of this repository to make sure we are free to use your code.

This is a quick process for you and protect everyone.

Thank you very much for fixing this issue!

**Comment by jsvd** [comment]
@barravi pinging you on this so we can get this merged quickly :)

**Comment by gytisgreitai** [comment]
@barravi maybe you would not be mad if someone else created same oneliner pull request?:)

**Comment by barravi** [comment]
by all means, go ahead, I thought this was already sorted out...

/V

**Comment by suyograo** [comment]
Fixed in #7

**Pull request closed without merging**
